team_lookup = {
'Abilene Chr':'Abilene Chr',
'Air Force':'Air Force',
'Akron':'Akron',
'Alabama':'Alabama',
'Alabama A&M':'Alabama A&M',
'Alabama St':'Alabama St',
'Albany NY':'Albany NY',
'Alcorn St':'Alcorn St',
'American':'American Univ',
'Appalachian St':'Appalachian St',
'Arizona':'Arizona',
'Arizona St':'Arizona St',
'Ark Little Rock':'Ark Little Rock',
'Arkansas-Pine Bluff':'Ark Pine Bluff',
'Arkansas':'Arkansas',
'Arkansas St':'Arkansas St',
'Army':'Army',
'Auburn':'Auburn',
'Austin Peay':'Austin Peay',
'Ball St':'Ball St',
'Baylor':'Baylor',
'Belmont':'Belmont',
'Bethune-Cookman':'Bethune-Cookman',
'Binghamton':'Binghamton',
'Birmingham So':'Birmingham So',
'Boise St':'Boise St',
'Boston College':'Boston College',
'Boston University':'Boston Univ',
'Bowling Green St':'Bowling Green',
'Bradley':'Bradley',
'Brown':'Brown',
'Bryant':'Bryant',
'Bucknell':'Bucknell',
'Buffalo':'Buffalo',
'Butler':'Butler',
'Brigham Young':'BYU',
'Central Michigan':'C Michigan',
'Cal Poly':'Cal Poly SLO',
'California':'California',
'Campbell':'Campbell',
'Canisius':'Canisius',
'Central Arkansas':'Cent Arkansas',
'Centenary':'Centenary',
'Central Connecticut St':'Central Conn',
'Charleston Southern':'Charleston So',
'Charlotte':'Charlotte',
'Chattanooga':'Chattanooga',
'Chicago St':'Chicago St',
'Cincinnati':'Cincinnati',
'Citadel':'Citadel',
'Clemson':'Clemson',
'Cleveland St':'Cleveland St',
'Coastal Carolina':'Coastal Car',
'College of Charleston':'Col Charleston',
'Colgate':'Colgate',
'Colorado':'Colorado',
'Colorado St':'Colorado St',
'Columbia':'Columbia',
'Connecticut':'Connecticut',
'Coppin St':'Coppin St',
'Cornell':'Cornell',
'Creighton':'Creighton',
'Cal St Bakersfield':'CS Bakersfield',
'Cal St Fullerton':'CS Fullerton',
'Cal St Northridge':'CS Northridge',
'Sacramento St':'CS Sacramento',
'Dartmouth':'Dartmouth',
'Davidson':'Davidson',
'Dayton':'Dayton',
'Delaware':'Delaware',
'Delaware St':'Delaware St',
'Denver':'Denver',
'DePaul':'DePaul',
'Detroit Mercy':'Detroit',
'Drake':'Drake',
'Drexel':'Drexel',
'Duke':'Duke',
'Duquesne':'Duquesne',
'Eastern Illinois':'E Illinois',
'Eastern Kentucky':'E Kentucky',
'Eastern Michigan':'E Michigan',
'Eastern Washington':'E Washington',
'East Carolina':'East Carolina',
'Edwardsville':'SIU Edwardsville',
'Elon':'Elon',
'East Tennessee St':'ETSU',
'Evansville':'Evansville',
'Fairleigh Dickinson':'F Dickinson',
'Fairfield':'Fairfield',
'Florida Atlantic':'FL Atlantic',
'Florida Gulf Coast':'FL Gulf Coast',
'Florida':'Florida',
'Florida A&M':'Florida A&M',
'Florida International':'Florida Intl',
'Florida St':'Florida St',
'Fordham':'Fordham',
'Fresno St':'Fresno St',
'Furman':'Furman',
'George Washington':'G Washington',
'Georgia Southern':'Ga Southern',
'Gardner-Webb':'Gardner Webb',
'George Mason':'George Mason',
'Georgetown':'Georgetown',
'Georgia':'Georgia',
'Georgia St':'Georgia St',
'Georgia Tech':'Georgia Tech',
'Gonzaga':'Gonzaga',
'Grambling':'Grambling',
'Grand Canyon':'Grand Canyon',
'Hampton':'Hampton',
'Hartford':'Hartford',
'Harvard':'Harvard',
'Hawaii':'Hawaii',
'High Point':'High Point',
'Hofstra':'Hofstra',
'Holy Cross':'Holy Cross',
'Houston':'Houston',
'Houston Baptist':'Houston Bap',
'Howard':'Howard',
'Idaho':'Idaho',
'Idaho St':'Idaho St',
'Illinois-Chicago':'IL Chicago',
'Illinois':'Illinois',
'Illinois St':'Illinois St',
'Indiana':'Indiana',
'Indiana St':'Indiana St',
'Iona':'Iona',
'Iowa':'Iowa',
'Iowa St':'Iowa St',
'IPFW':'IPFW',
'IUPUI':'IUPUI',
'Jackson St':'Jackson St',
'Jacksonville':'Jacksonville',
'Jacksonville St':'Jacksonville St',
'James Madison':'James Madison',
'Kansas':'Kansas',
'Kansas St':'Kansas St',
'Kennesaw St':'Kennesaw',
'Kent St':'Kent',
'Kentucky':'Kentucky',
'La Salle':'La Salle',
'Lafayette':'Lafayette',
'Lamar':'Lamar',
'Lehigh':'Lehigh',
'Liberty':'Liberty',
'Lipscomb':'Lipscomb',
'Long Beach St':'Long Beach St',
'Long Island University':'Long Island',
'Longwood':'Longwood',
'Louisiana Tech':'Louisiana Tech',
'Louisville':'Louisville',
'Loyola Marymount':'Loy Marymount',
'Loyola (MD)':'Loyola MD',
'Loyola (IL)':'Loyola-Chicago',
'Louisiana St':'LSU',
'Massachusetts-Lowell':'MA Lowell',
'Maine':'Maine',
'Manhattan':'Manhattan',
'Marist':'Marist',
'Marquette':'Marquette',
'Marshall':'Marshall',
'Maryland':'Maryland',
'Massachusetts':'Massachusetts',
'McNeese St':'McNeese St',
'Maryland-Eastern Shore':'MD E Shore',
'Memphis':'Memphis',
'Mercer':'Mercer',
'Miami (FL)':'Miami FL',
'Miami (OH)':'Miami OH',
'Michigan':'Michigan',
'Michigan St':'Michigan St',
'Middle Tennessee':'Middle Tenn St',
'Minnesota':'Minnesota',
'Mississippi':'Mississippi',
'Mississippi St':'Mississippi St',
'Missouri':'Missouri',
'Missouri-Kansas City':'Missouri KC',
'Missouri St':'Missouri St',
'Monmouth':'Monmouth NJ',
'Montana':'Montana',
'Montana St':'Montana St',
'Morehead St':'Morehead St',
'Morgan St':'Morgan St',
'Morris Brown':'Morris Brown',
'Mississippi Valley St':'MS Valley St',
"Mount St. Mary's":"Mt St Mary's",
'Murray St':'Murray St',
'N Colorado':'N Colorado',
'North Dakota St':'N Dakota St',
'N Illinois':'N Illinois',
'N Kentucky':'N Kentucky',
'Navy':'Navy',
'North Carolina A&T':'NC A&T',
'North Carolina Central':'NC Central',
'North Carolina St':'NC State',
'NE Illinois':'NE Illinois',
'Nebraska-Omaha':'NE Omaha',
'Nebraska':'Nebraska',
'Nevada':'Nevada',
'New Hampshire':'New Hampshire',
'New Mexico':'New Mexico',
'New Mexico St':'New Mexico St',
'New Orleans':'New Orleans',
'Niagara':'Niagara',
'Nicholls St':'Nicholls St',
'NJIT':'NJIT',
'Norfolk St':'Norfolk St',
'North Carolina':'North Carolina',
'North Dakota':'North Dakota',
'North Florida':'North Florida',
'North Texas':'North Texas',
'Northeastern':'Northeastern',
'N Arizona':'Northern Arizona',
'N Iowa':'Northern Iowa',
'Northwestern':'Northwestern',
'Northwestern St':'Northwestern LA',
'Notre Dame':'Notre Dame',
'Oakland':'Oakland',
'Ohio':'Ohio',
'Ohio St':'Ohio St',
'Oklahoma':'Oklahoma',
'Oklahoma St':'Oklahoma St',
'Old Dominion':'Old Dominion',
'Oral Roberts':'Oral Roberts',
'Oregon':'Oregon',
'Oregon St':'Oregon St',
'Pacific':'Pacific',
'Pennsylvania':'Penn',
'Penn St':'Penn St',
'Pepperdine':'Pepperdine',
'Pittsburgh':'Pittsburgh',
'Portland':'Portland',
'Portland St':'Portland St',
'Prairie View':'Prairie View',
'Presbyterian':'Presbyterian',
'Princeton':'Princeton',
'Providence':'Providence',
'Purdue':'Purdue',
'Quinnipiac':'Quinnipiac',
'Radford':'Radford',
'Rhode Island':'Rhode Island',
'Rice':'Rice',
'Richmond':'Richmond',
'Rider':'Rider',
'Robert Morris':'Robert Morris',
'Rutgers':'Rutgers',
'South Carolina St':'S Carolina St',
'South Dakota St':'S Dakota St',
'S Illinois':'S Illinois',
'Sacred Heart':'Sacred Heart',
'Sam Houston St':'Sam Houston St',
'Samford':'Samford',
'San Diego':'San Diego',
'San Diego St':'San Diego St',
'San Francisco':'San Francisco',
'San Jose St':'San Jose St',
'California-Santa Barbara':'Santa Barbara',
'Santa Clara':'Santa Clara',
'Savannah St':'Savannah St',
'South Carolina UpSt':'SC Upstate',
'Southeastern Louisiana':'SE Louisiana',
'Southeast Missouri St':'SE Missouri St',
'Seattle':'Seattle',
'Seton Hall':'Seton Hall',
'Stephen F. Austin':'SF Austin',
'Siena':'Siena',
'S Methodist':'SMU',
'South Alabama':'South Alabama',
'South Carolina':'South Carolina',
'South Dakota':'South Dakota',
'South Florida':'South Florida',
'S Mississippi':'Southern Miss',
'Southern':'Southern Univ',
'S Utah':'Southern Utah',
'St. Bonaventure':'St Bonaventure',
'St. Francis (NY)':'St Francis NY',
'Saint Francis (PA)':'St Francis PA',
"St. John's (NY)":"St John's",
"Saint Joseph's":"St Joseph's PA",
'Saint Louis':'St Louis',
"Saint Mary's (CA)":"St Mary's CA",
"Saint Peter's":"St Peter's",
'Stanford':'Stanford',
'Stetson':'Stetson',
'Stony Brook':'Stony Brook',
'Syracuse':'Syracuse',
'Texas A&M-Corpus Christi':'TAM C. Christi',
'Texas Christian':'TCU',
'Temple':'Temple',
'Tennessee':'Tennessee',
'Tennessee St':'Tennessee St',
'Tennessee Tech':'Tennessee Tech',
'Texas':'Texas',
'Texas A&M':'Texas A&M',
'Texas St':'Texas St',
'Texas Tech':'Texas Tech',
'Tennessee-Martin':'TN Martin',
'Toledo':'Toledo',
'Towson':'Towson',
'Troy':'Troy',
'Tulane':'Tulane',
'Tulsa':'Tulsa',
'Texas-Pan American':'TX Pan American',
'Texas Southern':'TX Southern',
'Alabama-Birmingham':'UAB',
'California-Davis':'UC Davis',
'California-Irvine':'UC Irvine',
'California-Riverside':'UC Riverside',
'Central Florida':'UCF',
'UCLA':'UCLA',
'Louisiana-Lafayette':'ULL',
'Louisiana-Monroe':'ULM',
'Maryland-Baltimore County':'UMBC',
'North Carolina-Asheville':'UNC Asheville',
'North Carolina-Greensboro':'UNC Greensboro',
'North Carolina-Wilmington':'UNC Wilmington',
'Nevada-Las Vegas':'UNLV',
'S California':'USC',
'Texas-Arlington':'UT Arlington',
'Texas-San Antonio':'UT San Antonio',
'Utah':'Utah',
'Utah St':'Utah St',
'Utah Valley':'Utah Valley',
'Texas-El Paso':'UTEP',
'Virginia Commonwealth':'VA Commonwealth',
'Valparaiso':'Valparaiso',
'Vanderbilt':'Vanderbilt',
'Vermont':'Vermont',
'Villanova':'Villanova',
'Virginia':'Virginia',
'Virginia Tech':'Virginia Tech',
'VMI':'VMI',
'Western Carolina':'W Carolina',
'Western Illinois':'W Illinois',
'Western Kentucky':'W Kentucky',
'Western Michigan':'W Michigan',
'W Salem St':'W Salem St',
'Wagner':'Wagner',
'Wake Forest':'Wake Forest',
'Washington':'Washington',
'Washington St':'Washington St',
'Weber St':'Weber St',
'West Virginia':'West Virginia',
'Green Bay':'WI Green Bay',
'Milwaukee':'WI Milwaukee',
'Wichita St':'Wichita St',
'William & Mary':'William & Mary',
'Winthrop':'Winthrop',
'Wisconsin':'Wisconsin',
'Wofford':'Wofford',
'Wright St':'Wright St',
'Wyoming':'Wyoming',
'Xavier':'Xavier',
'Yale':'Yale',
'Youngstown St':'Youngstown St',
'Incarnate Word':'Incarnate Word',
}
