team_lookup = {
'Abilene Chr':'Abilene Chr',
'Air Force':'Air Force',
'Akron':'Akron',
'Alabama':'Alabama',
'Alabama A&M':'Alabama A&M',
'Alabama St':'Alabama St',
'Albany NY':'Albany NY',
'Alcorn St':'Alcorn St',
'American Univ':'American',
'Appalachian St':'Appalachian St',
'Arizona':'Arizona',
'Arizona St':'Arizona St',
'Ark Little Rock':'Ark Little Rock',
'Ark Pine Bluff':'Arkansas-Pine Bluff',
'Arkansas':'Arkansas',
'Arkansas St':'Arkansas St',
'Army':'Army',
'Auburn':'Auburn',
'Austin Peay':'Austin Peay',
'Ball St':'Ball St',
'Baylor':'Baylor',
'Belmont':'Belmont',
'Bethune-Cookman':'Bethune-Cookman',
'Binghamton':'Binghamton',
'Birmingham So':'Birmingham So',
'Boise St':'Boise St',
'Boston College':'Boston College',
'Boston Univ':'Boston University',
'Bowling Green':'Bowling Green St',
'Bradley':'Bradley',
'Brown':'Brown',
'Bryant':'Bryant',
'Bucknell':'Bucknell',
'Buffalo':'Buffalo',
'Butler':'Butler',
'BYU':'Brigham Young',
'C Michigan':'Central Michigan',
'Cal Poly SLO':'Cal Poly',
'California':'California',
'Campbell':'Campbell',
'Canisius':'Canisius',
'Cent Arkansas':'Central Arkansas',
'Centenary':'Centenary',
'Central Conn':'Central Connecticut St',
'Charleston So':'Charleston Southern',
'Charlotte':'Charlotte',
'Chattanooga':'Chattanooga',
'Chicago St':'Chicago St',
'Cincinnati':'Cincinnati',
'Citadel':'Citadel',
'Clemson':'Clemson',
'Cleveland St':'Cleveland St',
'Coastal Car':'Coastal Carolina',
'Col Charleston':'College of Charleston',
'Colgate':'Colgate',
'Colorado':'Colorado',
'Colorado St':'Colorado St',
'Columbia':'Columbia',
'Connecticut':'Connecticut',
'Coppin St':'Coppin St',
'Cornell':'Cornell',
'Creighton':'Creighton',
'CS Bakersfield':'Cal St Bakersfield',
'CS Fullerton':'Cal St Fullerton',
'CS Northridge':'Cal St Northridge',
'CS Sacramento':'Sacramento St',
'Dartmouth':'Dartmouth',
'Davidson':'Davidson',
'Dayton':'Dayton',
'Delaware':'Delaware',
'Delaware St':'Delaware St',
'Denver':'Denver',
'DePaul':'DePaul',
'Detroit':'Detroit Mercy',
'Drake':'Drake',
'Drexel':'Drexel',
'Duke':'Duke',
'Duquesne':'Duquesne',
'E Illinois':'Eastern Illinois',
'E Kentucky':'Eastern Kentucky',
'E Michigan':'Eastern Michigan',
'E Washington':'Eastern Washington',
'East Carolina':'East Carolina',
'Edwardsville':'SIU Edwardsville',
'Elon':'Elon',
'ETSU':'East Tennessee St',
'Evansville':'Evansville',
'F Dickinson':'Fairleigh Dickinson',
'Fairfield':'Fairfield',
'FL Atlantic':'Florida Atlantic',
'FL Gulf Coast':'Florida Gulf Coast',
'Florida':'Florida',
'Florida A&M':'Florida A&M',
'Florida Intl':'Florida International',
'Florida St':'Florida St',
'Fordham':'Fordham',
'Fresno St':'Fresno St',
'Furman':'Furman',
'G Washington':'George Washington',
'Ga Southern':'Georgia Southern',
'Gardner Webb':'Gardner-Webb',
'George Mason':'George Mason',
'Georgetown':'Georgetown',
'Georgia':'Georgia',
'Georgia St':'Georgia St',
'Georgia Tech':'Georgia Tech',
'Gonzaga':'Gonzaga',
'Grambling':'Grambling',
'Grand Canyon':'Grand Canyon',
'Hampton':'Hampton',
'Hartford':'Hartford',
'Harvard':'Harvard',
'Hawaii':'Hawaii',
'High Point':'High Point',
'Hofstra':'Hofstra',
'Holy Cross':'Holy Cross',
'Houston':'Houston',
'Houston Bap':'Houston Baptist',
'Howard':'Howard',
'Idaho':'Idaho',
'Idaho St':'Idaho St',
'IL Chicago':'Illinois-Chicago',
'Illinois':'Illinois',
'Illinois St':'Illinois St',
'Indiana':'Indiana',
'Indiana St':'Indiana St',
'Iona':'Iona',
'Iowa':'Iowa',
'Iowa St':'Iowa St',
'IPFW':'IPFW',
'IUPUI':'IUPUI',
'Jackson St':'Jackson St',
'Jacksonville':'Jacksonville',
'Jacksonville St':'Jacksonville St',
'James Madison':'James Madison',
'Kansas':'Kansas',
'Kansas St':'Kansas St',
'Kennesaw':'Kennesaw St',
'Kent':'Kent St',
'Kentucky':'Kentucky',
'La Salle':'La Salle',
'Lafayette':'Lafayette',
'Lamar':'Lamar',
'Lehigh':'Lehigh',
'Liberty':'Liberty',
'Lipscomb':'Lipscomb',
'Long Beach St':'Long Beach St',
'Long Island':'Long Island University',
'Longwood':'Longwood',
'Louisiana Tech':'Louisiana Tech',
'Louisville':'Louisville',
'Loy Marymount':'Loyola Marymount',
'Loyola MD':'Loyola (MD)',
'Loyola-Chicago':'Loyola (IL)',
'LSU':'Louisiana St',
'MA Lowell':'Massachusetts-Lowell',
'Maine':'Maine',
'Manhattan':'Manhattan',
'Marist':'Marist',
'Marquette':'Marquette',
'Marshall':'Marshall',
'Maryland':'Maryland',
'Massachusetts':'Massachusetts',
'McNeese St':'McNeese St',
'MD E Shore':'Maryland-Eastern Shore',
'Memphis':'Memphis',
'Mercer':'Mercer',
'Miami FL':'Miami (FL)',
'Miami OH':'Miami (OH)',
'Michigan':'Michigan',
'Michigan St':'Michigan St',
'Middle Tenn St':'Middle Tennessee',
'Minnesota':'Minnesota',
'Mississippi':'Mississippi',
'Mississippi St':'Mississippi St',
'Missouri':'Missouri',
'Missouri KC':'Missouri-Kansas City',
'Missouri St':'Missouri St',
'Monmouth NJ':'Monmouth',
'Montana':'Montana',
'Montana St':'Montana St',
'Morehead St':'Morehead St',
'Morgan St':'Morgan St',
'Morris Brown':'Morris Brown',
'MS Valley St':'Mississippi Valley St',
"Mt St Mary's":"Mount St. Mary's",
'Murray St':'Murray St',
'N Colorado':'N Colorado',
'N Dakota St':'North Dakota St',
'N Illinois':'N Illinois',
'N Kentucky':'N Kentucky',
'Navy':'Navy',
'NC A&T':'North Carolina A&T',
'NC Central':'North Carolina Central',
'NC State':'North Carolina St',
'NE Illinois':'NE Illinois',
'NE Omaha':'Nebraska-Omaha',
'Nebraska':'Nebraska',
'Nevada':'Nevada',
'New Hampshire':'New Hampshire',
'New Mexico':'New Mexico',
'New Mexico St':'New Mexico St',
'New Orleans':'New Orleans',
'Niagara':'Niagara',
'Nicholls St':'Nicholls St',
'NJIT':'NJIT',
'Norfolk St':'Norfolk St',
'North Carolina':'North Carolina',
'North Dakota':'North Dakota',
'North Florida':'North Florida',
'North Texas':'North Texas',
'Northeastern':'Northeastern',
'Northern Arizona':'N Arizona',
'Northern Iowa':'N Iowa',
'Northwestern':'Northwestern',
'Northwestern LA':'Northwestern St',
'Notre Dame':'Notre Dame',
'Oakland':'Oakland',
'Ohio':'Ohio',
'Ohio St':'Ohio St',
'Oklahoma':'Oklahoma',
'Oklahoma St':'Oklahoma St',
'Old Dominion':'Old Dominion',
'Oral Roberts':'Oral Roberts',
'Oregon':'Oregon',
'Oregon St':'Oregon St',
'Pacific':'Pacific',
'Penn':'Pennsylvania',
'Penn St':'Penn St',
'Pepperdine':'Pepperdine',
'Pittsburgh':'Pittsburgh',
'Portland':'Portland',
'Portland St':'Portland St',
'Prairie View':'Prairie View',
'Presbyterian':'Presbyterian',
'Princeton':'Princeton',
'Providence':'Providence',
'Purdue':'Purdue',
'Quinnipiac':'Quinnipiac',
'Radford':'Radford',
'Rhode Island':'Rhode Island',
'Rice':'Rice',
'Richmond':'Richmond',
'Rider':'Rider',
'Robert Morris':'Robert Morris',
'Rutgers':'Rutgers',
'S Carolina St':'South Carolina St',
'S Dakota St':'South Dakota St',
'S Illinois':'S Illinois',
'Sacred Heart':'Sacred Heart',
'Sam Houston St':'Sam Houston St',
'Samford':'Samford',
'San Diego':'San Diego',
'San Diego St':'San Diego St',
'San Francisco':'San Francisco',
'San Jose St':'San Jose St',
'Santa Barbara':'California-Santa Barbara',
'Santa Clara':'Santa Clara',
'Savannah St':'Savannah St',
'SC Upstate':'South Carolina UpSt',
'SE Louisiana':'Southeastern Louisiana',
'SE Missouri St':'Southeast Missouri St',
'Seattle':'Seattle',
'Seton Hall':'Seton Hall',
'SF Austin':'Stephen F. Austin',
'Siena':'Siena',
'SMU':'S Methodist',
'South Alabama':'South Alabama',
'South Carolina':'South Carolina',
'South Dakota':'South Dakota',
'South Florida':'South Florida',
'Southern Miss':'S Mississippi',
'Southern Univ':'Southern',
'Southern Utah':'S Utah',
'St Bonaventure':'St. Bonaventure',
'St Francis NY':'St. Francis (NY)',
'St Francis PA':'Saint Francis (PA)',
"St John's":"St. John's (NY)",
"St Joseph's PA":"Saint Joseph's",
"St Louis":'Saint Louis',
"St Mary's CA":"Saint Mary's (CA)",
"St Peter's":"Saint Peter's",
'Stanford':'Stanford',
'Stetson':'Stetson',
'Stony Brook':'Stony Brook',
'Syracuse':'Syracuse',
'TAM C. Christi':'Texas A&M-Corpus Christi',
'TCU':'Texas Christian',
'Temple':'Temple',
'Tennessee':'Tennessee',
'Tennessee St':'Tennessee St',
'Tennessee Tech':'Tennessee Tech',
'Texas':'Texas',
'Texas A&M':'Texas A&M',
'Texas St':'Texas St',
'Texas Tech':'Texas Tech',
'TN Martin':'Tennessee-Martin',
'Toledo':'Toledo',
'Towson':'Towson',
'Troy':'Troy',
'Tulane':'Tulane',
'Tulsa':'Tulsa',
'TX Pan American':'Texas-Pan American',
'TX Southern':'Texas Southern',
'UAB':'Alabama-Birmingham',
'UC Davis':'California-Davis',
'UC Irvine':'California-Irvine',
'UC Riverside':'California-Riverside',
'UCF':'Central Florida',
'UCLA':'UCLA',
'ULL':'Louisiana-Lafayette',
'ULM':'Louisiana-Monroe',
'UMBC':'Maryland-Baltimore County',
'UNC Asheville':'North Carolina-Asheville',
'UNC Greensboro':'North Carolina-Greensboro',
'UNC Wilmington':'North Carolina-Wilmington',
'UNLV':'Nevada-Las Vegas',
'USC':'S California',
'UT Arlington':'Texas-Arlington',
'UT San Antonio':'Texas-San Antonio',
'Utah':'Utah',
'Utah St':'Utah St',
'Utah Valley':'Utah Valley',
'UTEP':'Texas-El Paso',
'VA Commonwealth':'Virginia Commonwealth',
'Valparaiso':'Valparaiso',
'Vanderbilt':'Vanderbilt',
'Vermont':'Vermont',
'Villanova':'Villanova',
'Virginia':'Virginia',
'Virginia Tech':'Virginia Tech',
'VMI':'VMI',
'W Carolina':'Western Carolina',
'W Illinois':'Western Illinois',
'W Kentucky':'Western Kentucky',
'W Michigan':'Western Michigan',
'W Salem St':'W Salem St',
'Wagner':'Wagner',
'Wake Forest':'Wake Forest',
'Washington':'Washington',
'Washington St':'Washington St',
'Weber St':'Weber St',
'West Virginia':'West Virginia',
'WI Green Bay':'Green Bay',
'WI Milwaukee':'Milwaukee',
'Wichita St':'Wichita St',
'William & Mary':'William & Mary',
'Winthrop':'Winthrop',
'Wisconsin':'Wisconsin',
'Wofford':'Wofford',
'Wright St':'Wright St',
'Wyoming':'Wyoming',
'Xavier':'Xavier',
'Yale':'Yale',
'Youngstown St':'Youngstown St',
'Incarnate Word':'Incarnate Word',
}