team_lookup = {
'South Carolina Upstate':'SC Upstate',
 'UC Santa Barbara':'Santa Barbara',
 'Arkansas Pine Bluff':'Ark Pine Bluff',
 'Central Michigan':'C Michigan',
 'IUPU Fort Wayne':'IPFW',
 "St. Mary's":"St Mary's CA",
 'Illinois Chicago':"IL Chicago",
 'Texas Pan American':'TX Pan American',
 'Florida Atlantic':'FL Atlantic',
 'Cal St. Northridge':'CS Northridge',
 'Houston Baptist':'Houston Bap',
 'St. Francis NY':'St Francis NY',
 'Northern Illinois':'N Illinois',
 'St. Francis PA':'St Francis PA',
 'Virginia Military Inst':'VMI',
 'MD Baltimore County':'UMBC',
 'Arkansas Little Rock':'Ark Little Rock',
 'Central Arkansas':'Cent Arkansas',
 'American':'American Univ',
 'Sacramento St':'CS Sacramento',
 'Kennesaw St':'Kennesaw',
 'Prairie View A&M':'Prarie View',
 'NC Wilmington':'UNC Wilmington',
 'Georgia Southern':'Ga Southern',
 'Texas Arlington':'UT Arlington',
 'St. Louis':'St Louis',
 'Tennessee Martin':'TN Martin',
 'Nevada Las Vegas':'UNLV',
 'Missouri Kansas City':'Missouri KC',
 'Loyola Chicago':'Loyola-Chicago',
 'Southern Mississippi':'Southern Miss',
 'Maryland Eastern Shore':'MD E Shore',
 'Western Illinois':'W Illinois',
 'Fairleigh Dickinson':'F Dickinson',
 'Southern Illinois':'S Illinois',
 'Louisiana St':'LSU',
 'NC Asheville':'UNC Asheville',
 'Bethune Cookman':'Bethune-Cookman',
 'Cal Poly':'Cal Poly SLO',
 "St. Peter's":"St Peter's",
 "North Dakota St.":"N Dakota St",
 'College of Charleston':'Col Charleston',
 'Eastern Illinois':'E Illinois',
 'Kent St':'Kent',
 "St. John's":"St John's",
 'Eastern Washington':'E Washington',
 'Texas Southern':'TX Southern',
 'Southeast Missouri St':'SE Missouri St',
 'Western Carolina':'W Carolina',
 'Eastern Kentucky':'E Kentucky',
 'Southern California':'USC',
 'Charleston Southern':'Charleston So',
 'Wisconsin Green Bay':'WI Green Bay',
 'Florida International':'Florida Intl',
 'North Carolina Central':'NC Central',
 'Central Connecticut':'Central Conn',
 'Virginia Commonwealth':'VA Commonwealth',
 'Cal St. Fullerton':'CS Fullerton',
 'Southeastern Louisiana':'SE Louisiana',
 'Coastal Carolina':'Coastal Car',
 'North Carolina A&T':'NC A&T',
 'Louisiana Monroe':'ULM',
 'The Citadel':'Citadel',
 'SIU Edwardsville':'Edwardsville',
 'Northern Colorado':'N Colorado',
 'Middle Tennessee':'Middle Tenn St',
 "Saint Joseph's":"St Joseph's PA",
 'Texas A&M Corpus Chris':'TAM C. Christi',
 'Loyola Marymount':'Loy Marymount',
 'Monmouth':'Monmouth NJ',
 'Southern':'Southern Univ',
 'Pennsylvania':'Penn',
 'Wisconsin Milwaukee':'WI Milwaukee',
 'Eastern Michigan':'E Michigan',
 'Texas San Antonio':'UT San Antonio',
 'St. Bonaventure':'St Bonaventure',
 'NC Greensboro':'UNC Greensboro',
 'Nebraska Omaha':'NE Omaha',
 'Western Michigan':'W Michigan',
 'Northwestern St':'Northwestern LA',
 'Albany':'Albany NY',
 'Florida Gulf Coast':'FL Gulf Coast',
 'South Carolina St':'S Carolina St',
 'North Carolina St':'NC State',
 'Texas Christian':'TCU',
 'Boston University':'Boston Univ',
 'Central Florida':'UCF',
 "Mount St. Mary's":"Mt St Mary's",
 'South Dakota St':'S Dakota St',
 'Cal St. Bakersfield':'CS Bakersfield',
 'George Washington':'G Washington',
 'NJ Inst of Technology':'NJIT',
 'Stephen F. Austin':'SF Austin',
 'Texas El Paso':'UTEP',
 'Southern Methodist':'SMU',
 'Brigham Young':'BYU',
 'North Dakota St':'N Dakota St',
 'Louisiana Lafayette':'ULL',
 'Western Kentucky':'W Kentucky',
 'East Tennessee St':'ETSU',
 'Mississippi Valley St':'MS Valley St',
 'Winston Salem St':'W Salem St',
 'Birmingham Southern':'Birmingham So',
 'Utah Valley St':'Utah Valley'
}