team_lookup = {
'Abilene Chr':'Abilene Chr',
'Grand Canyon':'Grand Canyon',
'Seattle':'Seattle',
'Morris Brown':'Morris Brown',
'MA Lowell':'MA Lowell',
'Prairie View':'Prairie View A&M',
'North Dakota':'North Dakota',
'South Dakota':'South Dakota',
'NE Illinois':'NE Illinois',
'Incarnate Word':'Incarnate Word',
'N Kentucky':'N Kentucky',
'SC Upstate':'South Carolina Upstate',
'Santa Barbara': 'UC Santa Barbara',
'Ark Pine Bluff': ['Arkansas Pine Bluff','Arkansas-Pine Bluff'],
'C Michigan': 'Central Michigan',
'IPFW': 'IUPU Fort Wayne',
"St Mary's CA": ["St. Mary's","Saint Mary's (CA)"],
"IL Chicago": ['Illinois Chicago','Illinois-Chicago'],
'TX Pan American': 'Texas Pan American',
'FL Atlantic': 'Florida Atlantic',
'CS Northridge': 'Cal St. Northridge',
'Houston Bap': 'Houston Baptist',
'St Francis NY': 'St. Francis NY',
'N Illinois': 'Northern Illinois',
'St Francis PA': 'St. Francis PA',
'VMI': 'Virginia Military Inst',
'UMBC': 'MD Baltimore County',
'Ark Little Rock': 'Arkansas Little Rock',
'Cent Arkansas': 'Central Arkansas',
'American Univ': 'American',
'CS Sacramento': 'Sacramento St',
'Kennesaw': 'Kennesaw St',
'Prarie View': 'Prairie View A&M',
'UNC Wilmington': ['NC Wilmington','North Carolina-Wilmington'],
'Ga Southern': 'Georgia Southern',
'UT Arlington': 'Texas Arlington',
'St Louis': ['St. Louis','Saint Louis'],
'TN Martin': 'Tennessee Martin',
'UNLV': ['Nevada Las Vegas','Nevada-Las Vegas'],
'Missouri KC': 'Missouri Kansas City',
'Loyola-Chicago': ['Loyola Chicago','Loyola (IL)'],
'Southern Miss': 'Southern Mississippi',
'MD E Shore': 'Maryland Eastern Shore',
'W Illinois': 'Western Illinois',
'F Dickinson': 'Fairleigh Dickinson',
'S Illinois': 'Southern Illinois',
'LSU': 'Louisiana St',
'UNC Asheville': ['NC Asheville','North Carolina-Asheville'],
'Bethune-Cookman': 'Bethune Cookman',
'Cal Poly SLO': 'Cal Poly',
"St Peter's": ["St. Peter's","Saint Peter's"],
'Col Charleston': 'College of Charleston',
'E Illinois': 'Eastern Illinois',
'Kent': 'Kent St',
"St John's": "St. John's",
'E Washington': 'Eastern Washington',
'TX Southern': 'Texas Southern',
'SE Missouri St': 'Southeast Missouri St',
'W Carolina': 'Western Carolina',
'E Kentucky': 'Eastern Kentucky',
'USC': ['Southern California','S California'],
'Charleston So': 'Charleston Southern',
'WI Green Bay': 'Wisconsin Green Bay',
'Florida Intl': 'Florida International',
'NC Central': 'North Carolina Central',
'Central Conn': ['Central Connecticut','Central Connecticut St'],
'VA Commonwealth': ['VCU','Virginia Commonwealth'],
'CS Fullerton': 'Cal St. Fullerton',
'SE Louisiana': 'Southeastern Louisiana',
'Coastal Car': 'Coastal Carolina',
'NC A&T': 'North Carolina A&T',
'ULM': 'Louisiana Monroe',
'Citadel': 'The Citadel',
'Edwardsville': 'SIU Edwardsville',
'N Colorado': 'Northern Colorado',
'Middle Tenn St': 'Middle Tennessee',
"St Joseph's PA": "Saint Joseph's",
'TAM C. Christi': ['Texas A&M Corpus Chris','Texas A&M-Corpus Christi'],
'Loy Marymount': 'Loyola Marymount',
'Monmouth NJ': 'Monmouth',
'Southern Univ': 'Southern',
'Penn': 'Pennsylvania',
'WI Milwaukee': ['Wisconsin Milwaukee','Milwaukee'],
'E Michigan': 'Eastern Michigan',
'UT San Antonio': ['Texas San Antonio','Texas-San Antonio'],
'St Bonaventure': 'St. Bonaventure',
'UNC Greensboro': ['NC Greensboro','North Carolina-Greensboro'],
'NE Omaha': 'Nebraska Omaha',
'W Michigan': 'Western Michigan',
'Northwestern LA': 'Northwestern St',
'Albany NY': 'Albany',
'FL Gulf Coast': 'Florida Gulf Coast',
'S Carolina St': 'South Carolina St',
'NC State': 'North Carolina St',
'TCU': 'Texas Christian',
'Boston Univ': 'Boston University',
'UCF': 'Central Florida',
"Mt St Mary's": "Mount St. Mary's",
'S Dakota St': 'South Dakota St',
'CS Bakersfield': 'Cal St. Bakersfield',
'G Washington': 'George Washington',
'NJIT': 'NJ Inst of Technology',
'SF Austin': 'Stephen F. Austin',
'UTEP': ['Texas El Paso','Texas-El Paso'],
'SMU': ['Southern Methodist','S Methodist'],
'BYU': ['Brigham Young','BYU'],
'N Dakota St': 'North Dakota St',
'ULL': ['Louisiana Lafayette','Louisiana-Lafayette'],
'W Kentucky': 'Western Kentucky',
'ETSU': 'East Tennessee St',
'MS Valley St': 'Mississippi Valley St',
'W Salem St': 'Winston Salem St',
'Birmingham So': ['Birmingham Southern','Birmingham-Southern'],
'Utah Valley': 'Utah Valley St',
"North Carolina":"North Carolina",
"Memphis":"Memphis",
"Connecticut":"Connecticut",
"Louisville":"Louisville",
"Pittsburgh":"Pittsburgh",
"Missouri":"Missouri",
"Gonzaga":"Gonzaga",
"Michigan St":"Michigan St",
"West Virginia":"West Virginia",
"Kansas":"Kansas",
"Duke":"Duke",
"UCLA":"UCLA",
"Oklahoma":"Oklahoma",
"Villanova":"Villanova",
"Syracuse":"Syracuse",
"Arizona St":"Arizona St",
"Washington":"Washington",
"Purdue":"Purdue",
"Marquette":"Marquette",
"Xavier":"Xavier",
"Clemson":"Clemson",
"Texas":"Texas",
"Illinois":"Illinois",
"Wake Forest":"Wake Forest",
"Georgetown":"Georgetown",
"Oklahoma St":"Oklahoma St",
"Wisconsin":"Wisconsin",
"Utah":"Utah",
"Tennessee":"Tennessee",
"California":"California",
"San Diego St":"San Diego St",
"Baylor":"Baylor",
"Washington St":"Washington St",
"Florida St":"Florida St",
"Ohio St":"Ohio St",
"Notre Dame":"Notre Dame",
"New Mexico":"New Mexico",
"Miami FL":["Miami FL",'Miami (FL)'],
"Arizona":"Arizona",
"Florida":"Florida",
"Kansas St":"Kansas St",
"Butler":"Butler",
"Texas A&M":"Texas A&M",
"Temple":"Temple",
"UAB":["UAB",'Alabama-Birmingham'],
"Stanford":"Stanford",
"Michigan":"Michigan",
"Minnesota":"Minnesota",
"Kentucky":"Kentucky",
"Maryland":"Maryland",
"Auburn":"Auburn",
"Utah St":"Utah St",
"Penn St":"Penn St",
"Siena":"Siena",
"Cleveland St":"Cleveland St",
"Mississippi St":"Mississippi St",
"Illinois St":"Illinois St",
"Tulsa":"Tulsa",
"Nebraska":"Nebraska",
"Virginia Tech":"Virginia Tech",
"Davidson":"Davidson",
"South Carolina":"South Carolina",
"Boston College":"Boston College",
"Northwestern":"Northwestern",
"Rhode Island":"Rhode Island",
"Houston":"Houston",
"Seton Hall":"Seton Hall",
"Niagara":"Niagara",
"Creighton":"Creighton",
"Vanderbilt":"Vanderbilt",
"Dayton":"Dayton",
"Providence":"Providence",
"Northern Iowa":["Northern Iowa",'N Iowa'],
"Vermont":"Vermont",
"Cincinnati":"Cincinnati",
"Duquesne":"Duquesne",
"Oral Roberts":"Oral Roberts",
"George Mason":"George Mason",
"Old Dominion":"Old Dominion",
"Iowa":"Iowa",
"Akron":"Akron",
"Georgia Tech":"Georgia Tech",
"Texas Tech":"Texas Tech",
"Alabama":"Alabama",
"Wright St":"Wright St",
"Mississippi":"Mississippi",
"Northeastern":"Northeastern",
"Nevada":"Nevada",
"Oakland":"Oakland",
"Cornell":"Cornell",
"Virginia":"Virginia",
"Oregon St":"Oregon St",
"Miami OH":["Miami OH",'Miami (OH)'],
"La Salle":"La Salle",
"Portland":"Portland",
"Iowa St":"Iowa St",
"Pacific":"Pacific",
"Richmond":"Richmond",
"Weber St":"Weber St",
"Robert Morris":"Robert Morris",
"Bradley":"Bradley",
"Belmont":"Belmont",
"Buffalo":"Buffalo",
"Sam Houston St":"Sam Houston St",
"Portland St":"Portland St",
"Arkansas":"Arkansas",
"Jacksonville":"Jacksonville",
"New Mexico St":"New Mexico St",
"Evansville":"Evansville",
"Wichita St":"Wichita St",
"Massachusetts":"Massachusetts",
"Drexel":"Drexel",
"Wyoming":"Wyoming",
"South Florida":"South Florida",
"Murray St":"Murray St",
"Bowling Green":"Bowling Green",
"James Madison":"James Madison",
"Rutgers":"Rutgers",
"Santa Clara":"Santa Clara",
"Charlotte":"Charlotte",
"Louisiana Tech":"Louisiana Tech",
"Drake":"Drake",
"Morgan St":"Morgan St",
"Morehead St":"Morehead St",
"Marshall":"Marshall",
"Boise St":"Boise St",
"Lipscomb":"Lipscomb",
"Oregon":"Oregon",
"Tulane":"Tulane",
"Utah Valley":"Utah Valley",
"North Texas":"North Texas",
"Idaho":"Idaho",
"Binghamton":"Binghamton",
"Sacred Heart":"Sacred Heart",
"Colorado":"Colorado",
"Rider":"Rider",
"Holy Cross":"Holy Cross",
"Fairfield":"Fairfield",
"Stony Brook":"Stony Brook",
"Long Beach St":"Long Beach St",
"Hofstra":"Hofstra",
"Nicholls St":"Nicholls St",
"San Diego":"San Diego",
"IUPUI":"IUPUI",
"Montana":"Montana",
"Ohio":"Ohio",
"Troy":["Troy","Troy St"],
"Colorado St":"Colorado St",
"South Alabama":"South Alabama",
"Manhattan":"Manhattan",
"Radford":"Radford",
"Indiana St":"Indiana St",
"Idaho St":"Idaho St",
"Austin Peay":"Austin Peay",
"San Jose St":"San Jose St",
"Missouri St":"Missouri St",
"DePaul":"DePaul",
"Iona":"Iona",
"Georgia":"Georgia",
"Delaware":"Delaware",
"Denver":"Denver",
"Hawaii":"Hawaii",
"Fresno St":"Fresno St",
"East Carolina":"East Carolina",
"Alabama St":"Alabama St",
"Liberty":"Liberty",
"Texas St":"Texas St",
"Indiana":"Indiana",
"UC Irvine":"UC Irvine",
"Lamar":"Lamar",
"Valparaiso":"Valparaiso",
"Youngstown St":"Youngstown St",
"UC Davis":"UC Davis",
"Georgia St":"Georgia St",
"UC Riverside":"UC Riverside",
"Navy":"Navy",
"Canisius":"Canisius",
"Mercer":"Mercer",
"Air Force":"Air Force",
"Chattanooga":"Chattanooga",
"William & Mary":"William & Mary",
"Loyola MD":["Loyola MD","Loyola (MD)"],
"Southern Utah":"Southern Utah",
"Long Island":["Long Island",'LIU Brooklyn'],
"Montana St":"Montana St",
"Wofford":"Wofford",
"Arkansas St":"Arkansas St",
"Rice":"Rice",
"Tennessee Tech":"Tennessee Tech",
"Northern Arizona":"Northern Arizona",
"San Francisco":"San Francisco",
"Campbell":"Campbell",
"Yale":"Yale",
"McNeese St":"McNeese St",
"Harvard":"Harvard",
"Ball St":"Ball St",
"Centenary":"Centenary",
"Towson":"Towson",
"Marist":"Marist",
"Chicago St":"Chicago St",
"Samford":"Samford",
"Gardner Webb":"Gardner Webb",
"New Hampshire":"New Hampshire",
"Jackson St":"Jackson St",
"Princeton":"Princeton",
"Appalachian St":"Appalachian St",
"Lehigh":"Lehigh",
"Stetson":"Stetson",
"Jacksonville St":"Jacksonville St",
"Coppin St":"Coppin St",
"Presbyterian":"Presbyterian",
"Wagner":"Wagner",
"Quinnipiac":"Quinnipiac",
"Columbia":"Columbia",
"Tennessee St":"Tennessee St",
"Hampton":"Hampton",
"Detroit":"Detroit",
"Winthrop":"Winthrop",
"New Orleans":"New Orleans",
"Army":"Army",
"Maine":"Maine",
"Elon":"Elon",
"Bucknell":"Bucknell",
"Norfolk St":"Norfolk St",
"Pepperdine":"Pepperdine",
"Toledo":"Toledo",
"Brown":"Brown",
"Dartmouth":"Dartmouth",
"High Point":"High Point",
"Colgate":"Colgate",
"Hartford":"Hartford",
"Lafayette":"Lafayette",
"Longwood":"Longwood",
"Delaware St":"Delaware St",
"Fordham":"Fordham",
"Savannah St":"Savannah St",
"Furman":"Furman",
"Bryant":"Bryant",
"Howard":"Howard",
"Florida A&M":"Florida A&M",
"North Florida":"North Florida",
"Alabama A&M":"Alabama A&M",
"Alcorn St":"Alcorn St",
"Grambling":"Grambling"}